# Generated by Django 5.0.7 on 2026-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchis_rf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Изображение'),
        ),
    ]
