# Generated by Django 5.0.7 on 2026-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchis_rf', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('transfer', 'Перевод по номеру телефона'), ('qr_prepayment', 'Предоплата по QR-коду'), ('mir_card', 'Оплата картой МИР'), ('office_postpayment', 'Постоплата в офисе организации')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
